# Generated by Django 2.2.6 on 2022-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220922_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=15, verbose_name='Текст'),
        ),
    ]
